name: test
on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name:  install
      working-directory: ./MobileApp
      run: npm ci
    - name:  build 
      working-directory: ./MobileApp
      run: npm run build --if-present
    - name:  test 
      working-directory: ./MobileApp
      run: npm test
